### ISSUE TITLE
chrome placeholder visible

### ISSUE THREAD

**Issue by bhh** [krisnoble/Portamento#2]
it seems to show the chrome placeholders even if they should be behind the portamento div. any idea if that is portamento related?

ok probably a chrome issue in general http://jsfiddle.net/jethrolarson/V58A2/
just wondering if you can think of a solution

**Comment by derekallard** [comment]
This isn't a portamento issue bhh, and you can work around it with z-index if you need to.

http://jsfiddle.net/V58A2/1/

**Comment by bhh** [comment]
thx for answering. thought i tested it. must have done something wrong in my app

**Comment by derekallard** [comment]
My pleasure!
