### ISSUE TITLE
IE 7 Issues

### ISSUE THREAD

**Issue by Nick-GDM** [krisnoble/Portamento#4]
Hi There,

I am using this JS and it works fine in all browsers apart from IE7, are there any known issues with a fix available?

The issues I am having is that the div is just stuck and doesnt float when scrolling down the page. Any ideas?

Thanks in advance.

**Comment by krisnoble** [comment]
Hi Nick

Sounds weird.. could you put some code up on JSfiddle or similar so I can check it out please?

Cheers :)
