### ISSUE TITLE
IE not working; not adding 'fixed' class

### ISSUE THREAD

**Issue by andjules** [krisnoble/Portamento#5]
I'm testing IE7 & IE8 and not getting anywhere with Portamento. Working wonderfully on Chrome & Safari & FF.
What I'm seeing is that the target DIV is getting wrapped with #portamento-container as expected, but when I scroll up, the target DIV is not getting assigned the .fixed class as it does in non-IE browsers. Wondering what to do next?

**Comment by krisnoble** [comment]
Hi there

Odd one that - can you stick your code up on jsfiddle or similar so I can check it out please?

Thanks!

**Comment by andjules** [comment]
Thanks for getting back to me.
I've not spent any time with jsfiddle, but I can point you to my staging site & the js file where I call portamento.
I'm using portamento on a drupal site (which currently limits me to jQuery 1.5.2), so at the beginning of my theme's javascript file, I figure out whether the admin toolbar (a lot like wordpress') is active (when signed in as an admin) or not, and adjust the portamento 'gap' accordingly. Then I instantiate portamento, then I do some z-index manipulation which I seemed to need for my 'megamenus', then on to other jQuery functions.
http://d7a.fundzen.com/sites/all/themes/noodle/client/fsc7/fsc7.js
try pages like: http://d7a.fundzen.com/about-us or http://d7a.fundzen.com/media-room/audio-video
It's a staging site so there is still a little polish to be applied, but hopefully you'll see portamento working wonderfully in non IE browsers.

**Comment by krisnoble** [comment]
Thanks for the link and info - I'll check it out and get back to you :)

**Comment by krisnoble** [comment]
Hey again

Sorry for the delay.. have you made some changes to the code? It works fine for me in IE8 but in IE7 mode the "share" button is way off to the right, causing a horizontal scrollbar, which in turn stops Portamento from working.

I think if you fix that "share" button it should work - I tried to use the IE developer tools to verify it but they leave a lot to be desired! :)

Let me know how you get on!
